comment:
  require_changes: yes
coverage:
  status:
    patch:
      default: false
      tests:
        target: 100%
        paths: "tests/"
      core:
        paths: "cloudbot/"
        target: 100%
      plugins:
        paths: "plugins/"
    project:
      tests:
        target: 100%
        paths: "tests/"
      core:
        paths: "cloudbot/"
      plugins:
        paths: "plugins/"
